on:
  schedule:
    # 每个月15号进行发布
    - cron: '0 0 15 * *'
  push:
    branches:
      - master

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2

      - name: 安装Dart
        uses: dart-lang/setup-dart@v1

      - name: 安装依赖
        run: dart pub get

      - name: 更新数据
        run: dart run scripts/run.dart

      - name: 获取版本号
        run: |
          echo "version=$(awk -F': ' '/version:/ {gsub("\\+", "+", $2); print $2}' pubspec.yaml)" >> "$GITHUB_ENV"

      - name: 打印版本号
        run: |-
          echo "version: ${{ env.version }}"

      - name: 提交代码
        run: |
          git config --local user.email "${{ secrets.MY_EMAIL }}"
          git config --local user.name "${{ secrets.MY_NAME }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "${{ env.version }}"
          git push


      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.version }}
          draft: false
          allowUpdates: true
          token: ${{ secrets.TOKEN }}
